llama:    
  templates:
      crawl:
        company_info: |

        product_info: |

        system: |

        prompt: |

        company_info_default: | 
                              company info: Our company is called KT, and we primarily provide internet and telecommunications services. 
                              Our main competitors are SK Telecom and LG U+.

        product_info_default: |
                              product info: "KT Internet, KT GiGA Internet, and KT 10GiGA Internet are wired internet services provided by KT. They hold the top position in the market with a 40.8% market share.

                              As for the product offerings:

                              KT Internet Super Premium offers a maximum speed of 10Gbps in both upload and download, using FTTH optical LAN technology.
                              KT Internet Premium Plus provides a maximum speed of 5Gbps in both directions, also utilizing FTTH technology.
                              KT Internet Premium offers speeds of up to 2.5Gbps in both upload and download, using FTTH optical LAN.
                              KT Internet Essence delivers a maximum bidirectional speed of 1Gbps via optical LAN.
                              KT Internet Basic offers speeds of up to 500Mbps in both directions, making it one of the fastest gigabit internet options.
                              KT Internet Slim Plus offers the most budget-friendly plan among gigabit internet options, with speeds limited to 200Mbps in both upload and download.
                              KT Internet Slim uses FTTH technology to provide a maximum bidirectional speed of 100Mbps."

        prompt_default: |
                        If the entered text is in Korean, translate it into English and tell me if it's related to kt or kt products. Always start your response with 'yes' if it is, and 'no' if it's not.

        
          
        system_default: |
                        You must distinguish among South Korea's mobile telecommunication companies (skt, kt, lg u+).
                        You must answer based on your judgment according to the question.
                        Only 'yes' or 'no' responses are acceptable. Any other response will not be tolerated.

      params:
        top_k: 1
        max_new_tokens: 2
        num_return_sequences: 1

chatgpt:
  templates:
    conversation:

      document: |

      document_default: |
                        내용 : {page_content}, 날짜 : {날짜}
      
      condense: |
                
      condense_default: |
                        Rephrase the conversation and the follow up query to be a standalone query, in its original language.

      system: |

      system_default: |
                      You are an expert of industry analysis. answer about the input by referring the following context : {context}

    report:
      prompt: |

      prompt_default: |
                      Develop a analysis report in korean about the company, product or service, Structure of report is follwing format
                      Executive Summary: Provide a concise overview of the report's findings and recommendations.  
                      Study Introduction: Introduce the company and its background, including its mission, vision, and core values.
                      Methodology: Explain the research methods, data sources, and analytical tools used.
                      Review of Statistics: Give a detailed analysis of each component, including market analysis, SWOT analysis, 5 forces model, BCG matrix, P.E.S.T.E.L analysis, 3C analysis and Business Model Canvas, etc.
                      Conclusion: Give a summary of the main findings and insights derived from the analysis
                      References: Citations of the sources used in the report, ensuring credibility and transparency
                      
                      Here is opinions about the company, product or service
                      {context}

      document: |
                 
      document_default: |
                        내용 : {page_content}, 날짜 : {날짜}

    params:
      model: gpt-3.5-turbo #gpt-4


embedding:
  params: None
  


  
  