llama:
  templates:
    crawl:
      company_info: ''
      product_info: ''
      system: ''
      prompt: ''
      company_info_default: "company info: Our company is called KT, and we primarily\
        \ provide internet and telecommunications services. \nOur main competitors\
        \ are SK Telecom and LG U+.\n"
      product_info_default: 'product info: "KT Internet, KT GiGA Internet, and KT
        10GiGA Internet are wired internet services provided by KT. They hold the
        top position in the market with a 40.8% market share.


        As for the product offerings:


        KT Internet Super Premium offers a maximum speed of 10Gbps in both upload
        and download, using FTTH optical LAN technology.

        KT Internet Premium Plus provides a maximum speed of 5Gbps in both directions,
        also utilizing FTTH technology.

        KT Internet Premium offers speeds of up to 2.5Gbps in both upload and download,
        using FTTH optical LAN.

        KT Internet Essence delivers a maximum bidirectional speed of 1Gbps via optical
        LAN.

        KT Internet Basic offers speeds of up to 500Mbps in both directions, making
        it one of the fastest gigabit internet options.

        KT Internet Slim Plus offers the most budget-friendly plan among gigabit internet
        options, with speeds limited to 200Mbps in both upload and download.

        KT Internet Slim uses FTTH technology to provide a maximum bidirectional speed
        of 100Mbps."

        '
      prompt_default: 'If the entered text is in Korean, translate it into English
        and tell me if it''s related to kt or kt products. Always start your response
        with ''yes'' if it is, and ''no'' if it is not.

        '
      system_default: 'You must distinguish among South Korea mobile telecommunication
        companies (skt, kt, lg u+).

        You must answer based on your judgment according to the question.

        Only yes or no responses are acceptable. Any other response will not be tolerated.

        '
    params:
      top_k: 1
      max_new_tokens: 1
      num_return_sequences: 1
chatgpt:
  templates:
    conversation:
      document: '

        '
      document_default: '내용 : {page_content}, 날짜 : {날짜}

        '
      condense: '

        '
      condense_default: 'Rephrase the conversation and the follow up query to be a
        standalone query, in its original language.

        '
      system: '

        '
      system_default: 'You are an expert of industry analysis. answer about the input
        by referring the following context : {context}

        '
    report:
      prompt: ''
      prompt_default: "당신은 산업 분석의 전문가입니다. 아래 양식에 맞게 보고서를 쓰세요. \
        \ *Title\n*Executive Summary  \n *Study Introduction\
        \  *Methodology  \n *Review of Statistics  Give a detailed analysis of each\
        \ component, including market analysis, SWOT  analysis, 5 forces model, BCG\
        \ matrix, P.E.S.T.E.L analysis, 3C analysis  and Business Model Canvas, etc.\n\
        \ *Conclusion *References  \n 반드시 제시된 분석방법들에 대한 결과를 자세히 써주세요.\n  위의 양식에\
        \ 알맞게 KT인터넷에 대한 장점과 단점, 개선점, 미래 전략, SKT, LGU+ 같은 경쟁사와의 비교 등을 담은 보고서를 반드시 한국어로\
        \ 써주시기 바랍니다.\n  KT인터넷에 대한 다음 의견들을 참고해서 보고서를 쓰기 바랍니다. {context}"
      document: '내용 : {page_content}, 날짜 : {날짜}

        '
      document_default: '내용 : {page_content}, 날짜 : {날짜}

        '
    params:
      model: gpt-3.5-turbo
embedding:
  params: None
